Update XComGame.int
Grobobobo/ayy-lmao-lwotc-prototype pull request #17
Opened 2021-04-10 12:39 UTC by specopsdameme

Just another mild change based on personal preferences.

2021-04-10 21:51 UTC, Grobobobo requested changes
Just some lines.

2021-04-10 21:51 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +LocFlyOverText="SEND THESE INFIDELS TO THEIR GRAVES"
I like the mordhau reference more.

2021-04-10 21:51 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +LocFlyOverText="Nanomachines, son!"
This flyover never displays, so the change is irrelevant, the actual ability is  'damagecontrol'

2021-04-11 11:28 UTC, specopsdameme commented on Ayylmaolwotc/Localization/XComGame.int
> +LocFlyOverText="Nanomachines, son!"
Just a quick precaution, in case something happens.
Besides, if that's a passive, then why there's LocFlyOverText there?

2021-04-11 12:45 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +LocFlyOverText="Nanomachines, son!"
Dunno, lots of flyover text is unused. If it was used, it would trigger at the beginning of each mission.

2021-04-11 13:21 UTC, Grobobobo requested changes

2021-04-11 13:21 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +m_arrDifficultyDescStrings[0]="A difficulty handcrafted for game journalists."
I'd rather you add that to baby mode, like "A difficulty appropriate for players that wants a \"cinematic experience\" or game journalists."

2021-04-13 15:52 UTC, Grobobobo requested changes
Fix those 2 things And I'll merge

2021-04-13 15:52 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +m_arrDifficultyDescStrings[0]="Are you for real."
I like the question mark more.

2021-04-13 15:52 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +m_arrDifficultyDescStrings[3]="The real game, designed for tactical and strategic geniuses living in concrete bunkers. Completing a campaign on the other \"difficulties\" does not count."
I like the old legend text more.

2021-04-14 16:39 UTC, merged