Update Localization Descriptions
Grobobobo/ayy-lmao-lwotc-prototype pull request #29
Opened 2021-05-10 16:17 UTC by specopsdameme

Current changes to description include:
- Tandem Warheads 
- Executioner 
- Gunner
- Ranger
- Waterworld Objective
- ADVENT FIrewalls
- Spectre's Horror
- Muton Elite Corpse
- Chosen's Keen

And potential more.

2021-05-10 19:10 UTC, Grobobobo requested changes
Sorry for being a little harsh, I'm having trouble explaining why some of these don't fit that well

2021-05-10 19:10 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +Description="Delays the current Dank Event projects by <Ability:PRIORITY_DATA_DARK_EVENT_EXTENSION_HOURS/> weeks." ; this too, unless we really do retain vanilla Dank Events delays
Let's remove them then

2021-05-10 19:10 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +LocLongDescription="Makes your team hate you, but who are you to deny the joys of bullying a weakened ayy? Confers +<Ability:EXECUTIONER_AIM_BONUS/> aim and +<Ability:EXECUTIONER_CRIT_BONUS/> critica
Don't like it.

2021-05-10 19:10 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +LocLongDescription="Does basically nothing lmao, unless you want to venture into the cursed lands of ini editing..."
Don't like it either, it's funny because the description is super short.

2021-05-10 19:10 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +ClassSummary="The backbone of any squad and fireteam, Rangers are masters of the rifle and may be trained to use it in offensive and defensive capacities. Their sawed-off secondary is also useful in
Don't explain the joke.

2021-05-10 19:10 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> +BriefSummary="These Ayyliens sit atop the Dickhead internal hierarchy. Unlike Viagras, it's all natural, baby. Well, probably. Most likely."
Not good either.

2021-05-10 19:10 UTC, Grobobobo commented on Ayylmaolwotc/Localization/XComGame.int
> -QuoteTextAuthor="- Dr. Tygan"
I think tygan saying it of all people is funny, But this is fine too.

2021-05-11 02:01 UTC, specopsdameme commented on Ayylmaolwotc/Localization/XComGame.int
> +BriefSummary="These Ayyliens sit atop the Dickhead internal hierarchy. Unlike Viagras, it's all natural, baby. Well, probably. Most likely."
Personally, I'd like to keep it. It's kinda like a prelude to the Elite's autopsy.

2021-05-17 13:15 UTC, merged